export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    PRODUCT_DETAILS : "PRODUCT_DETAILS",
    ADD_TO_CART : "ADD_TO_CART",
    INCREASE_ITEM_QTY: "INCREASE_ITEM_QTY",
    DECREASE_ITEM_QTY :"DECREASE_ITEM_QTY",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    EMPTY_CART : "EMPTY_CART"
}